# Generated by Django 5.1.7 on 2025-06-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auctionimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='image',
        ),
    ]
