# Generated by Django 5.2 on 2025-05-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_of_notification',
            field=models.CharField(choices=[('post_like', 'Post like'), ('post_comment', 'Post comment'), ('Message_received', 'Message received')], max_length=50),
        ),
    ]
