# Generated by Django 5.1.7 on 2025-06-05 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedScrapPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Metal', 'Metal'), ('Wood', 'Wood'), ('Glass', 'Glass'), ('Textile', 'Textile'), ('Electronic', 'Electronic'), ('Paper', 'Paper'), ('Furniture', 'Furniture'), ('Plastic', 'Plastic')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('delivery', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='scrap_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saved_by', models.ManyToManyField(related_name='saved_scrap_posts', through='scrapPosts.SavedScrapPost', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='savedscrappost',
            name='scrap_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_scrap_posts', to='scrapPosts.scrappost'),
        ),
        migrations.AlterUniqueTogether(
            name='savedscrappost',
            unique_together={('user', 'scrap_post')},
        ),
    ]
