# Generated by Django 5.1.7 on 2025-06-14 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapPosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapPostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scrap_images/')),
                ('scrap_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='scrapPosts.scrappost')),
            ],
        ),
    ]
