/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/MpComponents/AppFooter.vue')['default']
    CartNavbar: typeof import('./src/components/CartComponents/CartItems.vue')['default']
    Categories: typeof import('./src/components/MpComponents/Categories.vue')['default']
    CategoryProducts: typeof import('./src/components/MpComponents/CategoryProducts.vue')['default']
    ElectronicsProducts: typeof import('./src/components/MpComponents/ElectronicsProducts.vue')['default']
    Footer: typeof import('./src/components/MpComponents/Footer.vue')['default']
    GlassProducts: typeof import('./src/components/MpComponents/GlassProducts.vue')['default']
    HelloWorld: typeof import('./src/components/MpComponents/HelloWorld.vue')['default']
    MainText: typeof import('./src/components/MpComponents/MainText.vue')['default']
    MetalProducts: typeof import('./src/components/MpComponents/MetalProducts.vue')['default']
    MpProducts: typeof import('./src/components/MpComponents/MpProducts.vue')['default']
    Navbar: typeof import('./src/components/MpComponents/Navbar.vue')['default']
    OtherPages: typeof import('./src/components/UPComponents/OtherPages.vue')['default']
    PlasticProducts: typeof import('./src/components/MpComponents/PlasticProducts.vue')['default']
    Product: typeof import('./src/components/MpComponents/Product.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SellCategories: typeof import('./src/components/SellComponents/SellCategories.vue')['default']
    SellInfo: typeof import('./src/components/SellComponents/SellInfo.vue')['default']
    SellNavbar: typeof import('./src/components/SellComponents/SellNavbar.vue')['default']
    SellQuote: typeof import('./src/components/SellComponents/SellQuote.vue')['default']
    TextileProducts: typeof import('./src/components/MpComponents/TextileProducts.vue')['default']
    UPFooter: typeof import('./src/components/UPComponents/UPFooter.vue')['default']
    UPInfo: typeof import('./src/components/UPComponents/UPInfo.vue')['default']
    UPNavbar: typeof import('./src/components/UPComponents/UPNavbar.vue')['default']
    WoodProducts: typeof import('./src/components/MpComponents/WoodProducts.vue')['default']
  }
}
