# Generated by Django 5.1.7 on 2025-06-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_saved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='saved_by',
        ),
        migrations.DeleteModel(
            name='SavedRepurposedPost',
        ),
    ]
