# Generated by Django 5.2 on 2025-05-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
