# Generated by Django 5.1.7 on 2025-06-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversationmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
