# Generated by Django 5.1.7 on 2025-04-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapyBack', '0004_alter_user_firstname_alter_user_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
