# Generated by Django 5.2 on 2025-05-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapyBack', '0005_alter_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
