# Generated by Django 5.2 on 2025-05-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapyBack', '0006_alter_user_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='animal_avatar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
