# Generated by Django 5.2 on 2025-05-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapyBack', '0007_user_animal_avatar_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='animal_avatar',
        ),
    ]
